# Generated by Django 4.1.4 on 2022-12-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_bio', '0002_alter_membersinfo_fee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersinfo',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Malaysia', 'Malaysia'), ('USA', 'USA')], default='India', max_length=255),
        ),
        migrations.AddField(
            model_name='membersinfo',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membersinfo',
            name='state',
            field=models.CharField(default='not given', max_length=255),
        ),
        migrations.AddField(
            model_name='membersinfo',
            name='street',
            field=models.CharField(default='not given', max_length=255),
        ),
        migrations.AddField(
            model_name='membersinfo',
            name='zip',
            field=models.IntegerField(default=0),
        ),
    ]
