# Generated by Django 4.1.4 on 2022-12-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_bio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersinfo',
            name='fee_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=10),
        ),
    ]
