# Generated by Django 4.1.4 on 2022-12-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_bio', '0003_membersinfo_country_membersinfo_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersinfo',
            name='batch_change',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='membersinfo',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='membersinfo',
            name='current_batch_slot',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='membersinfo',
            name='fee_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='membersinfo',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='membersinfo',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
